AddPackage aml-flash-tool
AddPackage arduino-ide
AddPackage arduino-avr-core
AddPackage arm-none-eabi-gcc
AddPackage dtc
AddPackage kicad
AddPackage kicad-library
AddPackage kicad-library-3d
AddPackage pmbootstrap
AddPackage screen
AddPackage simulide
AddPackage simulide-debug
