#!/bin/bash
result=$(echo -e "lock\nsleep\nhibernate\nlogoff\nreboot\npoweroff" | rofi -dmenu -font "Terminus (TTF) 12" )
case $result in
	"poweroff")
		poweroff
		;;
	"reboot")
		reboot
		;;
	"logoff")
		i3-msg exit
		;;
	"hibernate")
		dm-tool lock
		systemctl hibernate
		;;
	"sleep")
		dm-tool lock
		systemctl suspend
		;;
	"lock")
		dm-tool lock
		;;
esac

