#!/bin/sh
set -m

# Ser wallpaper
#feh --bg-fill /home/nikp123/Pictures/Wallpaper/i_actually_use/hd/autumn_orange_forestry.jpg
nitrogen --set-zoom-fill ~/Pictures/Wallpaper/desktop_hd/alena-aenami-stay-1k.jpg

#wpg -m

# Policy manager
lxpolkit &

# Manages the "everything bar"
mkfifo $I3SOCK.xob
tail -f $I3SOCK.xob | xob &

# Monitor "manager"
#./lid-check &

# Terminal emulator server? Yeah don't ask
#foot -s &

# Delay (if needed)
#sleep 1

#/usr/lib/kdeconnectd &
#kdeconnect-indicator &

# Nextcloud file sync
nextcloud --background &

# Music
if pgrep mpd &> /dev/null; then
    mpd &
    mpDris2 &
fi

# Mah visualizer
xava &

# VM audio
scream -p 4010 -u &

# Compositor
picom &

# Fixes dumb wallpaper problems with multimonitor on the MATE DE
#dumb-mate-wallpaper-fixer

# Notification manager
dunst &

# Detect when shit changes
~/.config/i3/scripts/monitor_notify autorandr --change &

# Change everything once
autorandr --change &

# Apparently Xresources doesnt load when started by "startx"
xrdb ~/.Xresources &

# Restore JACK server
#ray-daemon --session "Visualizer music" &

# Bar
#excalibar &

# Key remapping. THESE NEED TO RUN IN ORDER.
#xmodmap -e "clear lock"
##xmodmap -e "keycode 9 = Caps_Lock NoSymbol Caps_Lock" &
#xmodmap -e "keycode 66 = Escape NoSymbol Escape"
xmodmap -e "remove lock = Caps_Lock"
xmodmap -e "keycode 66 = Escape"

