IgnorePath /etc/.updated
IgnorePath /etc/.pwd.lock
IgnorePath /etc/ca-certificates/extracted
IgnorePath /etc/hostname
IgnorePath /etc/ld.so.cache
IgnorePath /etc/os-release
IgnorePath /etc/ssl/certs
IgnorePath /usr/lib/modules
IgnorePath /usr/lib/modules/*/vmlinuz
IgnorePath /usr/lib/udev/hwdb.bin
IgnorePath /usr/share/info/dir
IgnorePath /usr/share/man/mandoc.db
IgnorePath /usr/share/mime
IgnorePath /var/.updated
IgnorePath /var/lib/portables
IgnorePath /var/lib/private
IgnorePath /var/lib/systemd/backlight
IgnorePath /var/lib/systemd/catalog
IgnorePath /var/lib/systemd/coredump
IgnorePath /var/lib/systemd/ephemeral-trees
IgnorePath /var/lib/systemd/home
IgnorePath /var/lib/systemd/linger
IgnorePath /var/lib/systemd/pstore
IgnorePath /var/lib/systemd/rfkill
IgnorePath /var/lib/systemd/timesync
IgnorePath /var/tmp

# Known cache files
IgnorePath /usr/lib/gdk-pixbuf-2.0/2.10.0/loaders.cache
IgnorePath /usr/lib/gio/modules/giomodule.cache
IgnorePath /usr/lib/gtk-3.0/3.0.0/immodules.cache
IgnorePath /usr/lib/gtk-4.0/4.0.0/media/giomodule.cache
IgnorePath /usr/lib/gtk-4.0/4.0.0/printbackends/giomodule.cache
IgnorePath /usr/share/applications/mimeinfo.cache
IgnorePath /usr/share/glib-2.0/schemas/gschemas.compiled
IgnorePath /usr/share/icons/Adwaita/icon-theme.cache
IgnorePath /usr/share/icons/AdwaitaLegacy/icon-theme.cache
IgnorePath /usr/share/icons/hicolor/icon-theme.cache
