#!/bin/sh
DISPLAY=:0

wallpaper=$(find -type l -path "*Pictures/Wallpaper/i_actually_use/*" | sort -R | tail -1)
echo $wallpaper
#wal -i "$wallpaper" -b "#000000" --saturate 1.0
wal -i "$wallpaper" -b "#000000" --backend colorz --saturate 1.0   
swaymsg reload

