#!/bin/python

import os
import argparse
import subprocess

os.environ['API_USER'] = 'username'
os.environ['API_PASSWORD'] = 'secret'


file_list = os.environ['NAUTILUS_SCRIPT_SELECTED_FILE_PATHS'].split('\n')


convert_cmd = ["convert"]

# Appends files from env var to list
for i in file_list:
	convert_cmd += [i]

convert_cmd += ["My Document.pdf"]

# Debugging madness
#subprocess.run(["notify-send", str(convert_cmd)])

subprocess.run(convert_cmd)
