
# Required files
db_file            "~/.cache/mpd/database"
log_file           "~/.cache/mpd/log"

# Optional
music_directory    "~/Music"
#music_directory     "/media/ventoy/Music/"
playlist_directory "~/.config/mpd/playlists"
pid_file           "~/.cache/mpd/pid"
state_file         "~/.cache/mpd/state"
sticker_file       "~/.cache/mpd/sticker.sql"

#audio_output {
#      type        "alsa"
#      name        "ALSA sound card"
##      device      "pulse"
#      format             "44100:16:2"
#      mixer_type  "software"
#      buffer_time "100"
#}

audio_output_format "44100:16:2"

audio_output {
      type  "pulse"
      name  "PulseAudio"
      mixer_type  "hardware"
      buffer_time "1000"
}

audio_output {
      type               "fifo"
      name               "toggle_visualizer"
      path               "/tmp/mpd.fifo"
      buffer_time        "100"
}

playlist_plugin {
      name "soundcloud"
      enabled "true"
      apikey "xTfDvh31zDTOuDOwPxeODQB6HeUSicd8"
}

#password "thisisaverysecurepassword@read,add,control,admin"
