#!/bin/sh
set -m

#wpg -m

# Start Waybar FIRST
#waybar &

# Notification manager
#mako &
dunst &

# Policy manager
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# Session
openbox-session &

# Manages the "everything bar"
mkfifo $SWAYSOCK.wob
tail -f $SWAYSOCK.wob | wob &

# Monitor "manager"
#./lid-check &

# Terminal emulator server? Yeah don't ask
foot -s &

# Delay (if needed)
#sleep 1

#/usr/lib/kdeconnectd &
#kdeconnect-indicator &

# Nextcloud file sync
nextcloud --background &

# Music
if pgrep mpd &> /dev/null; then
    mpd &
    mpDris2 &
fi

# Mah visualizer
#xava &

# VM audio
scream -p 4010 -u &

# Turn off monitor when idle
swayidle -w \
    timeout 600 'swaymsg "output \* dpms off"' \
    resume 'swaymsg "output \* dpms on"' \
    lock '~/.config/sway/scripts/lock' \
    after-resume 'loginctl lock-session' &


