source ./fixes/btrfs-mount-options.sh
source ./fixes/change-mountpoint-to-media.sh
source ./fixes/create-media-dir.sh
source ./fixes/disable-lockout.sh
source ./fixes/disable-pc-speaker.sh
source ./fixes/fix-limits.sh
source ./fixes/fix-transfer-speeds.sh
source ./fixes/fix-usb-ssd-trim.sh
source ./fixes/laptop-mode.sh
source ./fixes/load-qemu-nbd-module.sh
source ./fixes/power-management.sh
source ./fixes/service-stop-time.sh
source ./fixes/suspend-then-hibernate.sh
source ./fixes/udev-permissions.sh
source ./fixes/wifi-powersave.sh
