#font = Hack Nerd Font:style=Regular:pixelsize=14:antialias=true:autohint=false
#font = Terminus:style=Medium:pixelsize=14:antialias=true:autohint=true
font = Source Code Pro:style=Medium:pixelsize=12:antialias=true:autohint=true
term = xterm

shell = /usr/bin/fish

[bell]
urgent = true

[colors]
alpha = 0.9

