#font = Hack Nerd Font:style=Regular:pixelsize=14:antialias=true:autohint=false
font = Terminus:style=Medium:pixelsize=14:antialias=false:autohint=false
term = xterm

shell = /usr/bin/fish

bell = set-urgency

[colors]
alpha = 0.9

